import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  Lightbulb, 
  DollarSign, 
  Target, 
  Calendar, 
  Rocket, 
  Sparkles,
  Download,
  Users,
  TrendingUp,
  MessageSquare,
  X
} from "lucide-react";
import { jsPDF } from "jspdf";

interface ReportData {
  creator_analysis: {
    niche: string;
    audience_vibe: string;
    unmet_needs: string[];
  };
  the_product: {
    name: string;
    type: string;
    one_sentence_pitch: string;
    suggested_price: string;
    estimated_revenue_potential: string;
  };
  launch_strategy: {
    pre_launch_hook: string;
    day_1_to_30_plan: Array<{ week: number; focus: string }>;
    viral_hooks: string[];
  };
}

interface ReportViewProps {
  report: ReportData;
  platform: string;
  url: string;
  onClose: () => void;
}

const ReportView = ({ report, platform, url, onClose }: ReportViewProps) => {
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(139, 92, 246); // Purple
    doc.text("ShadowOS Revenue Strategy", pageWidth / 2, y, { align: "center" });
    y += 15;

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated for: ${url}`, pageWidth / 2, y, { align: "center" });
    y += 20;

    // Creator Analysis Section
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Creator Analysis", 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.text(`Niche: ${report.creator_analysis.niche}`, 20, y);
    y += 8;

    doc.setFontSize(10);
    const audienceLines = doc.splitTextToSize(`Audience Vibe: ${report.creator_analysis.audience_vibe}`, pageWidth - 40);
    doc.text(audienceLines, 20, y);
    y += audienceLines.length * 6 + 8;

    doc.text("Unmet Needs:", 20, y);
    y += 6;
    report.creator_analysis.unmet_needs.forEach((need, i) => {
      const needLines = doc.splitTextToSize(`• ${need}`, pageWidth - 50);
      doc.text(needLines, 25, y);
      y += needLines.length * 6;
    });
    y += 10;

    // The Product Section
    doc.setFontSize(16);
    doc.text("The Product", 20, y);
    y += 10;

    doc.setFontSize(12);
    doc.setTextColor(139, 92, 246);
    doc.text(report.the_product.name, 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Type: ${report.the_product.type}`, 20, y);
    y += 6;

    const pitchLines = doc.splitTextToSize(`Pitch: ${report.the_product.one_sentence_pitch}`, pageWidth - 40);
    doc.text(pitchLines, 20, y);
    y += pitchLines.length * 6 + 4;

    doc.text(`Price: ${report.the_product.suggested_price}`, 20, y);
    y += 6;
    doc.text(`Revenue Potential: ${report.the_product.estimated_revenue_potential}`, 20, y);
    y += 15;

    // Launch Strategy Section
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(16);
    doc.text("30-Day Launch Strategy", 20, y);
    y += 10;

    doc.setFontSize(10);
    const hookLines = doc.splitTextToSize(`Pre-Launch Hook: ${report.launch_strategy.pre_launch_hook}`, pageWidth - 40);
    doc.text(hookLines, 20, y);
    y += hookLines.length * 6 + 8;

    doc.text("Weekly Plan:", 20, y);
    y += 6;
    report.launch_strategy.day_1_to_30_plan.forEach((item) => {
      doc.text(`Week ${item.week}: ${item.focus}`, 25, y);
      y += 6;
    });
    y += 10;

    if (y > 230) {
      doc.addPage();
      y = 20;
    }

    doc.text("Viral Hooks:", 20, y);
    y += 6;
    report.launch_strategy.viral_hooks.forEach((hook, i) => {
      const hookTextLines = doc.splitTextToSize(`${i + 1}. ${hook}`, pageWidth - 50);
      doc.text(hookTextLines, 25, y);
      y += hookTextLines.length * 6 + 2;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by ShadowOS • shadowos.app", pageWidth / 2, 285, { align: "center" });

    doc.save(`ShadowOS-Report-${Date.now()}.pdf`);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-primary" />
            Revenue Strategy Report
          </h2>
          <p className="text-muted-foreground text-sm mt-1">
            Analysis for {platform === 'youtube' ? 'YouTube' : 'Instagram'} creator
          </p>
        </div>
        <div className="flex gap-2">
          <Button onClick={handleDownloadPDF} variant="outline" className="gap-2">
            <Download className="h-4 w-4" />
            Download PDF
          </Button>
          <Button onClick={onClose} variant="ghost" size="icon">
            <X className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* Creator Analysis */}
      <Card className="border-border/50 bg-card/50 backdrop-blur-xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Users className="h-5 w-5 text-primary" />
            Creator Analysis
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap gap-2">
            <Badge variant="secondary" className="text-sm">
              {report.creator_analysis.niche}
            </Badge>
          </div>
          <div>
            <p className="text-sm text-muted-foreground mb-2">Audience Vibe</p>
            <p className="text-foreground">{report.creator_analysis.audience_vibe}</p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground mb-2 flex items-center gap-1">
              <Target className="h-4 w-4" />
              Audience Pain Points
            </p>
            <ul className="space-y-2">
              {report.creator_analysis.unmet_needs.map((need, index) => (
                <li key={index} className="flex items-start gap-2 text-foreground">
                  <span className="text-primary mt-1">•</span>
                  {need}
                </li>
              ))}
            </ul>
          </div>
        </CardContent>
      </Card>

      {/* The Product */}
      <Card className="border-primary/30 bg-gradient-to-br from-primary/5 to-transparent backdrop-blur-xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Lightbulb className="h-5 w-5 text-primary" />
            The Product Idea
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="text-xl font-bold text-primary">{report.the_product.name}</h3>
            <Badge variant="outline" className="mt-2">{report.the_product.type}</Badge>
          </div>
          <p className="text-foreground italic">"{report.the_product.one_sentence_pitch}"</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
            <div className="flex items-center gap-3 p-4 rounded-lg bg-background/50 border border-border/50">
              <DollarSign className="h-8 w-8 text-green-500" />
              <div>
                <p className="text-sm text-muted-foreground">Suggested Price</p>
                <p className="font-bold text-lg">{report.the_product.suggested_price}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-4 rounded-lg bg-background/50 border border-border/50">
              <TrendingUp className="h-8 w-8 text-primary" />
              <div>
                <p className="text-sm text-muted-foreground">Revenue Potential</p>
                <p className="font-bold text-lg">{report.the_product.estimated_revenue_potential}</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Launch Strategy */}
      <Card className="border-border/50 bg-card/50 backdrop-blur-xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <Rocket className="h-5 w-5 text-primary" />
            Launch Strategy
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="p-4 rounded-lg bg-primary/10 border border-primary/30">
            <p className="text-sm text-muted-foreground mb-1">Pre-Launch Hook</p>
            <p className="font-medium text-foreground">{report.launch_strategy.pre_launch_hook}</p>
          </div>

          <div>
            <h4 className="font-semibold mb-4 flex items-center gap-2">
              <Calendar className="h-4 w-4 text-primary" />
              30-Day Launch Calendar
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              {report.launch_strategy.day_1_to_30_plan.map((item) => (
                <div 
                  key={item.week} 
                  className="p-4 rounded-lg bg-background/50 border border-border/50 hover:border-primary/50 transition-colors"
                >
                  <p className="text-primary font-bold mb-1">Week {item.week}</p>
                  <p className="text-sm text-muted-foreground">{item.focus}</p>
                </div>
              ))}
            </div>
          </div>

          <div>
            <h4 className="font-semibold mb-4 flex items-center gap-2">
              <MessageSquare className="h-4 w-4 text-primary" />
              Viral Content Hooks
            </h4>
            <div className="space-y-2">
              {report.launch_strategy.viral_hooks.map((hook, index) => (
                <div 
                  key={index}
                  className="p-3 rounded-lg bg-background/50 border border-border/50 flex items-start gap-3"
                >
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/20 text-primary text-sm flex items-center justify-center font-medium">
                    {index + 1}
                  </span>
                  <p className="text-foreground">{hook}</p>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ReportView;
